"""
Generate a human-readable HTML report for a print job.

TECH DEBT:
- HTML only for MVP. PDF via WeasyPrint is ~50 MB extra dep — add when hospitals ask.
- No chart/image embedding yet (layer visualisation would be valuable).
- Template is inline string — move to Jinja2 when report gets complex.
"""
from datetime import datetime, timezone
from pathlib import Path
from typing import Any


_HTML_TEMPLATE = """\
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>BioPrint Report — {job_name}</title>
<style>
  body {{ font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif;
          max-width: 860px; margin: 40px auto; color: #1a1a1a; line-height: 1.6; }}
  h1   {{ font-size: 1.6rem; border-bottom: 2px solid #0057ff; padding-bottom: 8px; }}
  h2   {{ font-size: 1.1rem; color: #0057ff; margin-top: 2rem; }}
  table{{ border-collapse: collapse; width: 100%; margin: 1rem 0; }}
  th, td{{ border: 1px solid #ddd; padding: 8px 12px; text-align: left; }}
  th   {{ background: #f4f7ff; }}
  .pass{{ color: #1a7a1a; font-weight: 600; }}
  .fail{{ color: #c0392b; font-weight: 600; }}
  .warn{{ background: #fff8e1; border-left: 4px solid #f39c12; padding: 10px 14px;
          margin: 1rem 0; font-size: 0.9rem; }}
  footer{{ margin-top: 3rem; font-size: 0.8rem; color: #888; border-top: 1px solid #ddd;
           padding-top: 12px; }}
</style>
</head>
<body>
<h1>BioPrint Technical Report</h1>
<p><strong>Job:</strong> {job_name} &nbsp;|&nbsp;
   <strong>ID:</strong> {job_id} &nbsp;|&nbsp;
   <strong>Generated:</strong> {generated_at}</p>

<div class="warn">
  This report is a documentation aid generated by BioPrint software.
  It does not constitute regulatory approval. Review by a qualified Responsible
  Person is required before any clinical or research use.
</div>

<h2>Geometry</h2>
<table>
  <tr><th>Parameter</th><th>Value</th></tr>
  {geometry_rows}
</table>

<h2>Slicing</h2>
<table>
  <tr><th>Parameter</th><th>Value</th></tr>
  {slice_rows}
</table>

<h2>Compliance</h2>
<p>Regulation: <strong>{regulation_ref}</strong> &nbsp;|&nbsp;
   Overall: <span class="{overall_class}">{overall_label}</span></p>
<table>
  <tr><th>Check ID</th><th>Description</th><th>Result</th><th>Detail</th></tr>
  {compliance_rows}
</table>
{compliance_warnings}

<h2>G-code Artefact</h2>
<table>
  <tr><th>Parameter</th><th>Value</th></tr>
  {gcode_rows}
</table>

<footer>
  Generated by BioPrint v0.1.0 &mdash; Regulation reference: {regulation_ref}<br>
  {generated_at}
</footer>
</body>
</html>
"""


def generate_report(
    job_id: int,
    job_name: str,
    geometry: dict[str, Any],
    slice_data: dict[str, Any],
    compliance: dict[str, Any],
    gcode_meta: dict[str, Any] | None,
    output_path: Path,
) -> str:
    now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")

    geo_rows = _kv_rows({
        "X (mm)": geometry.get("x_mm"),
        "Y (mm)": geometry.get("y_mm"),
        "Z (mm)": geometry.get("z_mm"),
        "Volume (mm³)": geometry.get("volume_mm3"),
        "Surface area (mm²)": geometry.get("surface_area_mm2"),
        "Triangles": geometry.get("triangle_count"),
    })

    slice_rows = _kv_rows({
        "Layer height (mm)": slice_data.get("layer_height_mm"),
        "Layer count": slice_data.get("layer_count"),
    })

    checks = compliance.get("checks", [])
    comp_rows = "\n".join(
        f"<tr><td>{c['check_id']}</td><td>{c['description']}</td>"
        f"<td class=\"{'pass' if c['passed'] else 'fail'}\">{'PASS' if c['passed'] else 'FAIL'}</td>"
        f"<td>{c.get('detail') or ''}</td></tr>"
        for c in checks
    )

    overall = compliance.get("passed", False)
    warn_html = ""
    for w in compliance.get("warnings", []):
        warn_html += f'<div class="warn">{w}</div>\n'

    gcode_rows = _kv_rows({
        "Lines": gcode_meta.get("line_count") if gcode_meta else "—",
        "Estimated print time (s)": gcode_meta.get("estimated_print_time_s") if gcode_meta else "—",
        "File": gcode_meta.get("artifact_filename") if gcode_meta else "—",
    })

    html = _HTML_TEMPLATE.format(
        job_name=job_name,
        job_id=job_id,
        generated_at=now,
        geometry_rows=geo_rows,
        slice_rows=slice_rows,
        regulation_ref=compliance.get("regulation_ref", "EC 1394/2007"),
        overall_class="pass" if overall else "fail",
        overall_label="PASS" if overall else "FAIL",
        compliance_rows=comp_rows,
        compliance_warnings=warn_html,
        gcode_rows=gcode_rows,
    )

    output_path.write_text(html, encoding="utf-8")
    return output_path.name


def _kv_rows(data: dict) -> str:
    return "\n".join(
        f"<tr><td>{k}</td><td>{v if v is not None else '—'}</td></tr>"
        for k, v in data.items()
    )
