-- ─── agent_messages ──────────────────────────────────────────────────────────
-- Stores proactive messages generated by the compliance agent triggers.
-- These are surfaced in the AgentBar and the AgentSidebar history.

CREATE TABLE IF NOT EXISTS agent_messages (
  id               UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  organisation_id  UUID NOT NULL REFERENCES organisations(id) ON DELETE CASCADE,
  product_id       UUID REFERENCES products(id) ON DELETE CASCADE,
  message          TEXT NOT NULL,
  trigger_type     TEXT NOT NULL,          -- e.g. 'product_created', 'formula_saved'
  read             BOOLEAN NOT NULL DEFAULT false,
  created_at       TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Indexes for common query patterns
CREATE INDEX agent_messages_org_read_idx     ON agent_messages(organisation_id, read, created_at DESC);
CREATE INDEX agent_messages_product_idx      ON agent_messages(product_id, created_at DESC);

-- RLS: users can only access messages belonging to their organisation
ALTER TABLE agent_messages ENABLE ROW LEVEL SECURITY;

CREATE POLICY "agent_messages_select" ON agent_messages
  FOR SELECT USING (
    organisation_id IN (
      SELECT organisation_id FROM profiles WHERE id = auth.uid()
    )
  );

CREATE POLICY "agent_messages_insert" ON agent_messages
  FOR INSERT WITH CHECK (
    organisation_id IN (
      SELECT organisation_id FROM profiles WHERE id = auth.uid()
    )
  );

CREATE POLICY "agent_messages_update" ON agent_messages
  FOR UPDATE USING (
    organisation_id IN (
      SELECT organisation_id FROM profiles WHERE id = auth.uid()
    )
  );
